[tool.commitizen]
version_scheme = "semver"
version = "1.2.0"
version_files = [
  "Framework/PrimerKlarnaSDK/Sources/Version/version.swift:let PrimerKlarnaSDKVersion",
  "PrimerKlarnaSDK.podspec:spec.version"
]
