#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.2 effective-5.10 (swiftlang-6.2.0.19.9 clang-1700.3.19.1)
#ifndef KLARNAPAYMENTS_SWIFT_H
#define KLARNAPAYMENTS_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreFoundation;
@import Foundation;
@import KlarnaCore;
@import ObjectiveC;
@import UIKit;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="KlarnaPayments",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

@class NSCoder;
@class KlarnaExpressCheckoutButtonOptions;
@class UIView;
SWIFT_CLASS("_TtC14KlarnaPayments27KlarnaExpressCheckoutButton")
@interface KlarnaExpressCheckoutButton : UIControl
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (nonnull instancetype)initWithOptions:(KlarnaExpressCheckoutButtonOptions * _Nonnull)options OBJC_DESIGNATED_INITIALIZER;
- (void)willMoveToSuperview:(UIView * _Nullable)newSuperview;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end

SWIFT_CLASS("_TtC14KlarnaPayments48KlarnaExpressCheckoutButtonAuthorizationResponse")
@interface KlarnaExpressCheckoutButtonAuthorizationResponse : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Options for configuring the Klarna Express Checkout button.
/// \param sessionOptions Authorization params object with default values of each param.
///
/// \param returnURL The return URL which should be used for navigating users back to the app.
///
/// \param callback KlarnaExpressCheckoutButtonCallback object to get notified of key events happening to a product in a Klarna component
///
/// \param locale Localization, list of supported locales
/// https://docs.klarna.com/klarna-payments/before-you-start/data-requirements/puchase-countries-currencies-locales/#data-mapping
///
/// \param styleConfiguration Style configuration for the button including button theme, button shape and if the button is outlined or not.
/// Default theme is <code>DARK</code>, default shape is <code>ROUNDED_RECT</code> and default style is <code>FILLED</code>.
///
/// \param environment KlarnaEnvironment object to set the mode of SDK to run in
///
/// \param region KlarnaRegion object to set the geographic region for SDK’s API requests
///
/// \param theme KlarnaTheme object to set the theme for components
///
/// \param resourceEndpoint KlarnaResourceEndpoint object to set the resources endpoint configuration for the SDK
///
/// \param loggingLevel The SDK’s logging level
///
SWIFT_CLASS("_TtC14KlarnaPayments34KlarnaExpressCheckoutButtonOptions")
@interface KlarnaExpressCheckoutButtonOptions : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Style configuration for the Klarna Express Checkout button.
/// \param theme The theme of the button
///
/// \param shape The shape of the button
///
/// \param style The style of the button
///
SWIFT_CLASS("_TtC14KlarnaPayments45KlarnaExpressCheckoutButtonStyleConfiguration")
@interface KlarnaExpressCheckoutButtonStyleConfiguration : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Options for configuring a Klarna Express Checkout session.
SWIFT_CLASS("_TtC14KlarnaPayments35KlarnaExpressCheckoutSessionOptions")
@interface KlarnaExpressCheckoutSessionOptions : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// \param clientId Partner client ID from Merchant Portal.
///
/// \param autoFinalize If true, the session will be automatically finalized after the user authorizes the payment.
///
/// \param collectShippingAddress If true, the session will collect shipping address information.
///
/// \param sessionData session data to be passed to the backend.
///
SWIFT_CLASS("_TtCC14KlarnaPayments35KlarnaExpressCheckoutSessionOptions17ClientSideSession")
@interface ClientSideSession : KlarnaExpressCheckoutSessionOptions
@end

/// \param clientToken Client token generated by the backend for the server-side session. 
///
/// \param autoFinalize If true, the session will be automatically finalized after the user authorizes the payment.
///
/// \param collectShippingAddress If true, the session will collect shipping address information.
///
/// \param sessionData Optional session data to be passed to the backend.
///
SWIFT_CLASS("_TtCC14KlarnaPayments35KlarnaExpressCheckoutSessionOptions17ServerSideSession")
@interface ServerSideSession : KlarnaExpressCheckoutSessionOptions
@end

@class KlarnaPaymentView;
@class NSString;
@class KlarnaPaymentError;
/// An object that will be notified of events happening to a <code>KlarnaPaymentView</code>
/// If you’re integrating Klarna Payments natively, you’ll need to implement an instance of this
/// listener and initialize the <code>KlarnaPaymentView</code> with it.
/// warning:
/// Make sure you listen to to <code>klarnaFailed(inPaymentView:withError:)</code> for potential
/// fatal and non-fatal errors. If the error is not fatal, you can call the method again.
SWIFT_PROTOCOL("_TtP14KlarnaPayments26KlarnaPaymentEventListener_")
@protocol KlarnaPaymentEventListener
/// The <code>initialize()</code> function for this payment view was successful.
/// You can follow up by calling <code>load()</code> to render details for this method, or if this payment
/// method is already authorized, <code>loadPaymentReview()</code>.
/// \param paymentView The <code>KlarnaPaymentView</code> that was initialized.
///
- (void)klarnaInitializedWithPaymentView:(KlarnaPaymentView * _Nonnull)paymentView;
/// The <code>load()</code> function for this payment view was successful.
/// Payment view should be visible now. If the user chooses to pay with the payment method in
/// this view, call <code>authorize()</code>.
/// \param paymentView The <code>KlarnaPaymentView</code> that was loaded.
///
- (void)klarnaLoadedWithPaymentView:(KlarnaPaymentView * _Nonnull)paymentView;
/// The <code>loadPaymentReview()</code> function for this payment view was successful.
/// Payment view is rendering a description of what the payment method that was authorized.
/// \param paymentView The <code>KlarnaPaymentView</code> that renders a payment review.
///
- (void)klarnaLoadedPaymentReviewWithPaymentView:(KlarnaPaymentView * _Nonnull)paymentView;
/// An authorization was performed for the payment method in the payment view.
/// If you have an authorization token, you can create an order with your backend at this point.
/// note:
/// This method being called doesn’t necessarily mean that it was successful. You might need
/// to call <code>finalize()</code>, you might need to correct an error or there might be a fatal error.
/// \param paymentView The <code>KlarnaPaymentView</code> rendering the authorized payment method.
///
/// \param approved Is the session approved? If true, you should also get an <code>authToken</code>.
///
/// \param authToken Authorization token.
///
/// \param finalizeRequired If true, <code>finalize()</code> needs to be called.
///
- (void)klarnaAuthorizedWithPaymentView:(KlarnaPaymentView * _Nonnull)paymentView approved:(BOOL)approved authToken:(NSString * _Nullable)authToken finalizeRequired:(BOOL)finalizeRequired;
/// A reauthorization was performed for the payment method in the payment view.
/// If you have an authorization token, you can create an order with your backend at this point.
/// If the order is changed after this point. Call the view’s <code>reauthorize()</code> instead
/// of calling <code>authorize()</code> again.
/// note:
/// This method being called doesn’t mean that it was necessarily successful. If <code>klarnaAuthorized()</code>
/// previously returned true for <code>finalizeRequired</code>, you need to still call <code>finalize()</code>. There
/// might also be an error.
/// \param paymentView The <code>KlarnaPaymentView</code> rendering the reauthorized payment method.
///
/// \param approved Is the session reapproved? If true, you should also get a new <code>authToken</code>.
///
/// \param authToken Authorization token. You can use this to create an order.
///
- (void)klarnaReauthorizedWithPaymentView:(KlarnaPaymentView * _Nonnull)paymentView approved:(BOOL)approved authToken:(NSString * _Nullable)authToken;
/// The session for the payment method in this view has performed a finalize.
/// If it’s approved and you have an authorization token, you can create an order.
/// note:
/// You need to check for the <code>authToken</code> to make sure the session is finalized.
/// \param paymentView The <code>KlarnaPaymentView</code> rendering the finalized payment method.
///
/// \param approved Is the session reapproved? If true, you should also get a new <code>authToken</code>.
///
/// \param authToken Authorization token. You can use this to create an order.
///
- (void)klarnaFinalizedWithPaymentView:(KlarnaPaymentView * _Nonnull)paymentView approved:(BOOL)approved authToken:(NSString * _Nullable)authToken;
/// Called when a Payment View resized internally.
/// Update your constraints (or whatever solution you have) to match the layout.
/// \param paymentView The <code>KlarnaPaymentView</code> that resized.
///
/// \param newHeight The new height in points.
///
- (void)klarnaResizedWithPaymentView:(KlarnaPaymentView * _Nonnull)paymentView to:(CGFloat)newHeight;
/// Called if an error occured during some part of the flow.
/// If the error’s <code>invalidFields</code> property contains field names and the error isn’t fatal, you can:
/// <ol>
///   <li>
///     Prompt the user to get updated info for those fields.
///   </li>
///   <li>
///     Call the same method with those updated fields as additional data.
///   </li>
/// </ol>
/// warning:
/// Errors may or may not be fatal. If the error is fatal the <code>KlarnaPaymentView</code> should not be
/// displayed anymore.
/// \param paymentView The <code>KlarnaPaymentView</code> that the error occured in.
///
/// \param error Error that occurred.
///
- (void)klarnaFailedInPaymentView:(KlarnaPaymentView * _Nonnull)paymentView withError:(KlarnaPaymentError * _Nonnull)error;
@end

SWIFT_CLASS("_TtC14KlarnaPayments17KlarnaPaymentView")
@interface KlarnaPaymentView : UIView
/// Mark <code>init(frame:)</code> as <code>private</code> to prevent it being used to initialize the payment view.
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder SWIFT_UNAVAILABLE;
- (void)didMoveToWindow;
- (void)willMoveToSuperview:(UIView * _Nullable)newSuperview;
@end

@interface KlarnaPaymentView (SWIFT_EXTENSION(KlarnaPayments)) <KlarnaSingleComponent>
@end

@class NSURL;
@interface KlarnaPaymentView (SWIFT_EXTENSION(KlarnaPayments))
/// Initialize the <code>KlarnaPaymentView</code>.
/// \param clientToken Client token received from Klarna when creating the session.
///
/// \param returnUrl Your apps custom URL scheme <code>CFBundleURLSchemes</code>.
///
- (void)initializeWithClientToken:(NSString * _Nonnull)clientToken returnUrl:(NSURL * _Nonnull)returnUrl;
/// Initialize the <code>KlarnaPaymentView</code>.
/// \param clientToken Client token received from Klarna when creating the session.
///
- (void)initializeWithClientToken:(NSString * _Nonnull)clientToken;
/// Performs a pre-assessment for this payment method category. Loads content into the
/// <code>KlarnaPaymentView</code>.
/// note:
///
/// Any existing content in the view (e.g. if you already called <code>load()</code> before) will be
/// replaced.
/// \param jsonData An optional string with order data to update the session. Formatted as JSON.
///
- (void)loadWithJsonData:(NSString * _Nullable)jsonData;
/// Renders an overview of the payment terms that have been authorized.
/// If your checkout offers the customer an opportunity to review the order after the payment
/// step (e.g. an order review page) it can make sense to present the payment method the customer
/// selected on a previous page.
/// This gives the customer a change to review the payment method and its terms to the user.
/// note:
///
/// Any existing content in the view (e.g. if you already called <code>load()</code> before) will be
/// replaced.
/// note:
///
/// Currently only specific payment methods and countries may be supported.
/// warning:
///
/// The session should be authorized.
- (void)loadPaymentReview;
/// Authorizes the session and evaluates whether an order can be created.
/// Merchant’s delegate will be called with successful/unsuccessful result of authorization.
/// \param jsonData An optional string to update the session. Formatted as JSON.
///
- (void)authorizeWithJsonData:(NSString * _Nullable)jsonData;
/// Authorizes the session and evaluates whether an order can be created.
/// Merchant’s delegate will be called with successful/unsuccessful result of authorization.
/// \param autoFinalize An optional flag used to turn off auto-finalization for the direct bank transfer payment method.
///
/// \param jsonData An optional string to update the session. Formatted as JSON.
///
- (void)authorizeWithAutoFinalize:(BOOL)autoFinalize jsonData:(NSString * _Nullable)jsonData;
/// Reauthorizes the session.
/// Call this if session details (order or customer info) have changed after authorization.
/// Merchant’s delegate will be called with successful/unsuccessful result of reauthorization.
/// \param jsonData An optional json string to update the session.
///
- (void)reauthorizeWithJsonData:(NSString * _Nullable)jsonData;
/// Finalizes the session.
/// Call this if you called <code>authorize()</code> with <code>autoFinalize</code> set to <code>false</code> and results in
/// <code>finalizeRequired</code> with a <code>true</code> value.
/// Merchant’s delegate will be called with successful/unsuccessful result of finalization.
/// note:
///
/// Method is called <code>finalise</code> with an “s” to avoid conflicts with the <code>NSObject</code> method of
/// the same name.
/// \param jsonData An optional string to update the session. Formatted as JSON.
///
- (void)finaliseWithJsonData:(NSString * _Nullable)jsonData;
@end

@class KlarnaPaymentOptions;
@class KlarnaEnvironment;
@class KlarnaRegion;
@class KlarnaResourceEndpoint;
@interface KlarnaPaymentView (SWIFT_EXTENSION(KlarnaPayments))
/// Payment method category this view will be / is displaying.
@property (nonatomic, readonly, copy) NSString * _Nonnull category;
/// Informs whether this <code>KlarnaPaymentView</code> should be displayed to the customer.
/// Will be false until a successful load() call has been performed.
@property (nonatomic, readonly) BOOL isLoaded;
/// Informs whether this PaymentView’s content is loaded.
/// True by default. Once it becomes false, it will not become true again.
@property (nonatomic, readonly) BOOL isAvalable;
/// Options for Klarna Payments integration
@property (nonatomic, readonly, strong) KlarnaPaymentOptions * _Nonnull paymentOptions;
/// Create a Klarna Payment View
/// note:
///
/// Klarna payment view will be initialized with frame <code>.zero</code>,
/// auto layout is the recommended way to manage the view’s layout.
/// note:
///
/// When the payment view is initialized, this initializer <em>wont</em> call <code>initialize()</code>
/// automatically. You need to call initialize yourself.
/// \param category Category of payment methods to be loaded.
///
/// \param eventListener A listener object that will receive events from this view.
///
- (nonnull instancetype)initWithCategory:(NSString * _Nonnull)category eventListener:(id <KlarnaPaymentEventListener> _Nonnull)eventListener;
/// Create a Klarna Payment View
/// note:
///
/// Klarna payment view will be initialized with frame <code>.zero</code>,
/// auto layout is the recommended way to manage the view’s layout.
/// note:
///
/// When the payment view is initialized, this initializer <em>wont</em> call <code>initialize()</code>
/// automatically. You need to call initialize yourself.
/// \param category Category of payment methods to be loaded.
///
/// \param returnUrl Your app’s custom URL scheme, specified in your app’s <code>CFBundleURLSchemes</code> field in the Info.plist.
///
/// \param eventListener A listener object that will receive events from this view.
///
- (nonnull instancetype)initWithCategory:(NSString * _Nonnull)category returnUrl:(NSURL * _Nonnull)returnUrl eventListener:(id <KlarnaPaymentEventListener> _Nonnull)eventListener;
/// Create a Klarna Payment View
/// note:
///
/// Klarna payment view will be initialized with frame <code>.zero</code>,
/// auto layout is the recommended way to manage the view’s layout.
/// note:
///
/// When the payment view is initialized, this initializer <em>wont</em> call <code>initialize()</code>
/// automatically. You need to call initialize yourself.
/// \param category Category of payment methods to be loaded.
///
/// \param returnUrl Your app’s custom URL scheme, specified in your app’s <code>CFBundleURLSchemes</code> field in the Info.plist.
///
/// \param eventListener A listener object that will receive events from this view.
///
/// \param environment Initialises the SDK with the specified Environment. For possible values check <code>KlarnaEnvironment</code>.
///
/// \param region Initialises the SDK with a specified Region. For possible values check <code>KlarnaRegion</code>.
///
- (nonnull instancetype)initWithCategory:(NSString * _Nonnull)category returnUrl:(NSURL * _Nonnull)returnUrl eventListener:(id <KlarnaPaymentEventListener> _Nonnull)eventListener environment:(KlarnaEnvironment * _Nonnull)environment region:(KlarnaRegion * _Nonnull)region;
/// Create a Klarna Payment View
/// note:
///
/// Klarna payment view will be initialized with frame <code>.zero</code>,
/// auto layout is the recommended way to manage the view’s layout.
/// note:
///
/// When the payment view is initialized, this initializer <em>wont</em> call <code>initialize()</code>
/// automatically. You need to call initialize yourself.
/// \param category Category of payment methods to be loaded.
///
/// \param eventListener A listener object that will receive events from this view.
///
/// \param resourceEndpoint Initialises the SDK with an alternative endpoint.
///
- (nonnull instancetype)initWithCategory:(NSString * _Nonnull)category eventListener:(id <KlarnaPaymentEventListener> _Nonnull)eventListener resourceEndpoint:(KlarnaResourceEndpoint * _Nonnull)resourceEndpoint;
/// Create a Klarna Payment View
/// note:
///
/// Klarna payment view will be initialized with frame <code>.zero</code>,
/// auto layout is the recommended way to manage the view’s layout.
/// note:
///
/// When the payment view is initialized, this initializer <em>wont</em> call <code>initialize()</code>
/// automatically. You need to call initialize yourself.
/// \param category Category of payment methods to be loaded.
///
/// \param returnUrl Your apps custom URL scheme <code>CFBundleURLSchemes</code>.
///
/// \param eventListener A listener object that will receive events from this view.
///
/// \param resourceEndpoint Initialises the SDK with an alternative endpoint.
///
- (nonnull instancetype)initWithCategory:(NSString * _Nonnull)category returnUrl:(NSURL * _Nonnull)returnUrl eventListener:(id <KlarnaPaymentEventListener> _Nonnull)eventListener resourceEndpoint:(KlarnaResourceEndpoint * _Nonnull)resourceEndpoint;
@end

@protocol KlarnaEventHandler;
@protocol KlarnaSizingDelegate;
@class UIScrollView;
@interface KlarnaPaymentView (SWIFT_EXTENSION(KlarnaPayments)) <KlarnaStandaloneComponent>
@property (nonatomic, strong) KlarnaRegion * _Nullable region;
@property (nonatomic, strong) KlarnaEnvironment * _Nullable environment;
@property (nonatomic, strong) KlarnaResourceEndpoint * _Nonnull resourceEndpoint;
@property (nonatomic, copy) NSURL * _Nullable returnURL;
@property (nonatomic) enum KlarnaTheme theme;
@property (nonatomic, strong) id <KlarnaEventHandler> _Nullable eventHandler;
@property (nonatomic) enum KlarnaLoggingLevel loggingLevel;
@property (nonatomic, readonly, copy) NSSet<NSString *> * _Nonnull products;
@property (nonatomic, readonly) CGFloat contentHeight;
@property (nonatomic, strong) id <KlarnaSizingDelegate> _Nullable sizingDelegate;
@property (nonatomic) BOOL isScrollEnabled;
@property (nonatomic) UIEdgeInsets contentInset;
@property (nonatomic, readonly) CGPoint contentOffset;
@property (nonatomic) enum UIScrollViewContentInsetAdjustmentBehavior contentInsetAdjustmentBehavior SWIFT_AVAILABILITY(ios,introduced=11.0);
@property (nonatomic) enum UIScrollViewKeyboardDismissMode keyboardDismissMode;
@property (nonatomic, strong) UIScrollView * _Nullable parentScrollView;
@property (nonatomic) BOOL adjustsParentScrollViewInsets;
@end

SWIFT_CLASS("_TtC14KlarnaPayments22KlarnaPaymentViewDebug")
@interface KlarnaPaymentViewDebug : KlarnaPaymentView
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#elif defined(__x86_64__) && __x86_64__
// Generated by Apple Swift version 6.2 effective-5.10 (swiftlang-6.2.0.19.9 clang-1700.3.19.1)
#ifndef KLARNAPAYMENTS_SWIFT_H
#define KLARNAPAYMENTS_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreFoundation;
@import Foundation;
@import KlarnaCore;
@import ObjectiveC;
@import UIKit;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="KlarnaPayments",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

@class NSCoder;
@class KlarnaExpressCheckoutButtonOptions;
@class UIView;
SWIFT_CLASS("_TtC14KlarnaPayments27KlarnaExpressCheckoutButton")
@interface KlarnaExpressCheckoutButton : UIControl
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (nonnull instancetype)initWithOptions:(KlarnaExpressCheckoutButtonOptions * _Nonnull)options OBJC_DESIGNATED_INITIALIZER;
- (void)willMoveToSuperview:(UIView * _Nullable)newSuperview;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end

SWIFT_CLASS("_TtC14KlarnaPayments48KlarnaExpressCheckoutButtonAuthorizationResponse")
@interface KlarnaExpressCheckoutButtonAuthorizationResponse : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Options for configuring the Klarna Express Checkout button.
/// \param sessionOptions Authorization params object with default values of each param.
///
/// \param returnURL The return URL which should be used for navigating users back to the app.
///
/// \param callback KlarnaExpressCheckoutButtonCallback object to get notified of key events happening to a product in a Klarna component
///
/// \param locale Localization, list of supported locales
/// https://docs.klarna.com/klarna-payments/before-you-start/data-requirements/puchase-countries-currencies-locales/#data-mapping
///
/// \param styleConfiguration Style configuration for the button including button theme, button shape and if the button is outlined or not.
/// Default theme is <code>DARK</code>, default shape is <code>ROUNDED_RECT</code> and default style is <code>FILLED</code>.
///
/// \param environment KlarnaEnvironment object to set the mode of SDK to run in
///
/// \param region KlarnaRegion object to set the geographic region for SDK’s API requests
///
/// \param theme KlarnaTheme object to set the theme for components
///
/// \param resourceEndpoint KlarnaResourceEndpoint object to set the resources endpoint configuration for the SDK
///
/// \param loggingLevel The SDK’s logging level
///
SWIFT_CLASS("_TtC14KlarnaPayments34KlarnaExpressCheckoutButtonOptions")
@interface KlarnaExpressCheckoutButtonOptions : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Style configuration for the Klarna Express Checkout button.
/// \param theme The theme of the button
///
/// \param shape The shape of the button
///
/// \param style The style of the button
///
SWIFT_CLASS("_TtC14KlarnaPayments45KlarnaExpressCheckoutButtonStyleConfiguration")
@interface KlarnaExpressCheckoutButtonStyleConfiguration : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Options for configuring a Klarna Express Checkout session.
SWIFT_CLASS("_TtC14KlarnaPayments35KlarnaExpressCheckoutSessionOptions")
@interface KlarnaExpressCheckoutSessionOptions : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// \param clientId Partner client ID from Merchant Portal.
///
/// \param autoFinalize If true, the session will be automatically finalized after the user authorizes the payment.
///
/// \param collectShippingAddress If true, the session will collect shipping address information.
///
/// \param sessionData session data to be passed to the backend.
///
SWIFT_CLASS("_TtCC14KlarnaPayments35KlarnaExpressCheckoutSessionOptions17ClientSideSession")
@interface ClientSideSession : KlarnaExpressCheckoutSessionOptions
@end

/// \param clientToken Client token generated by the backend for the server-side session. 
///
/// \param autoFinalize If true, the session will be automatically finalized after the user authorizes the payment.
///
/// \param collectShippingAddress If true, the session will collect shipping address information.
///
/// \param sessionData Optional session data to be passed to the backend.
///
SWIFT_CLASS("_TtCC14KlarnaPayments35KlarnaExpressCheckoutSessionOptions17ServerSideSession")
@interface ServerSideSession : KlarnaExpressCheckoutSessionOptions
@end

@class KlarnaPaymentView;
@class NSString;
@class KlarnaPaymentError;
/// An object that will be notified of events happening to a <code>KlarnaPaymentView</code>
/// If you’re integrating Klarna Payments natively, you’ll need to implement an instance of this
/// listener and initialize the <code>KlarnaPaymentView</code> with it.
/// warning:
/// Make sure you listen to to <code>klarnaFailed(inPaymentView:withError:)</code> for potential
/// fatal and non-fatal errors. If the error is not fatal, you can call the method again.
SWIFT_PROTOCOL("_TtP14KlarnaPayments26KlarnaPaymentEventListener_")
@protocol KlarnaPaymentEventListener
/// The <code>initialize()</code> function for this payment view was successful.
/// You can follow up by calling <code>load()</code> to render details for this method, or if this payment
/// method is already authorized, <code>loadPaymentReview()</code>.
/// \param paymentView The <code>KlarnaPaymentView</code> that was initialized.
///
- (void)klarnaInitializedWithPaymentView:(KlarnaPaymentView * _Nonnull)paymentView;
/// The <code>load()</code> function for this payment view was successful.
/// Payment view should be visible now. If the user chooses to pay with the payment method in
/// this view, call <code>authorize()</code>.
/// \param paymentView The <code>KlarnaPaymentView</code> that was loaded.
///
- (void)klarnaLoadedWithPaymentView:(KlarnaPaymentView * _Nonnull)paymentView;
/// The <code>loadPaymentReview()</code> function for this payment view was successful.
/// Payment view is rendering a description of what the payment method that was authorized.
/// \param paymentView The <code>KlarnaPaymentView</code> that renders a payment review.
///
- (void)klarnaLoadedPaymentReviewWithPaymentView:(KlarnaPaymentView * _Nonnull)paymentView;
/// An authorization was performed for the payment method in the payment view.
/// If you have an authorization token, you can create an order with your backend at this point.
/// note:
/// This method being called doesn’t necessarily mean that it was successful. You might need
/// to call <code>finalize()</code>, you might need to correct an error or there might be a fatal error.
/// \param paymentView The <code>KlarnaPaymentView</code> rendering the authorized payment method.
///
/// \param approved Is the session approved? If true, you should also get an <code>authToken</code>.
///
/// \param authToken Authorization token.
///
/// \param finalizeRequired If true, <code>finalize()</code> needs to be called.
///
- (void)klarnaAuthorizedWithPaymentView:(KlarnaPaymentView * _Nonnull)paymentView approved:(BOOL)approved authToken:(NSString * _Nullable)authToken finalizeRequired:(BOOL)finalizeRequired;
/// A reauthorization was performed for the payment method in the payment view.
/// If you have an authorization token, you can create an order with your backend at this point.
/// If the order is changed after this point. Call the view’s <code>reauthorize()</code> instead
/// of calling <code>authorize()</code> again.
/// note:
/// This method being called doesn’t mean that it was necessarily successful. If <code>klarnaAuthorized()</code>
/// previously returned true for <code>finalizeRequired</code>, you need to still call <code>finalize()</code>. There
/// might also be an error.
/// \param paymentView The <code>KlarnaPaymentView</code> rendering the reauthorized payment method.
///
/// \param approved Is the session reapproved? If true, you should also get a new <code>authToken</code>.
///
/// \param authToken Authorization token. You can use this to create an order.
///
- (void)klarnaReauthorizedWithPaymentView:(KlarnaPaymentView * _Nonnull)paymentView approved:(BOOL)approved authToken:(NSString * _Nullable)authToken;
/// The session for the payment method in this view has performed a finalize.
/// If it’s approved and you have an authorization token, you can create an order.
/// note:
/// You need to check for the <code>authToken</code> to make sure the session is finalized.
/// \param paymentView The <code>KlarnaPaymentView</code> rendering the finalized payment method.
///
/// \param approved Is the session reapproved? If true, you should also get a new <code>authToken</code>.
///
/// \param authToken Authorization token. You can use this to create an order.
///
- (void)klarnaFinalizedWithPaymentView:(KlarnaPaymentView * _Nonnull)paymentView approved:(BOOL)approved authToken:(NSString * _Nullable)authToken;
/// Called when a Payment View resized internally.
/// Update your constraints (or whatever solution you have) to match the layout.
/// \param paymentView The <code>KlarnaPaymentView</code> that resized.
///
/// \param newHeight The new height in points.
///
- (void)klarnaResizedWithPaymentView:(KlarnaPaymentView * _Nonnull)paymentView to:(CGFloat)newHeight;
/// Called if an error occured during some part of the flow.
/// If the error’s <code>invalidFields</code> property contains field names and the error isn’t fatal, you can:
/// <ol>
///   <li>
///     Prompt the user to get updated info for those fields.
///   </li>
///   <li>
///     Call the same method with those updated fields as additional data.
///   </li>
/// </ol>
/// warning:
/// Errors may or may not be fatal. If the error is fatal the <code>KlarnaPaymentView</code> should not be
/// displayed anymore.
/// \param paymentView The <code>KlarnaPaymentView</code> that the error occured in.
///
/// \param error Error that occurred.
///
- (void)klarnaFailedInPaymentView:(KlarnaPaymentView * _Nonnull)paymentView withError:(KlarnaPaymentError * _Nonnull)error;
@end

SWIFT_CLASS("_TtC14KlarnaPayments17KlarnaPaymentView")
@interface KlarnaPaymentView : UIView
/// Mark <code>init(frame:)</code> as <code>private</code> to prevent it being used to initialize the payment view.
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder SWIFT_UNAVAILABLE;
- (void)didMoveToWindow;
- (void)willMoveToSuperview:(UIView * _Nullable)newSuperview;
@end

@interface KlarnaPaymentView (SWIFT_EXTENSION(KlarnaPayments)) <KlarnaSingleComponent>
@end

@class NSURL;
@interface KlarnaPaymentView (SWIFT_EXTENSION(KlarnaPayments))
/// Initialize the <code>KlarnaPaymentView</code>.
/// \param clientToken Client token received from Klarna when creating the session.
///
/// \param returnUrl Your apps custom URL scheme <code>CFBundleURLSchemes</code>.
///
- (void)initializeWithClientToken:(NSString * _Nonnull)clientToken returnUrl:(NSURL * _Nonnull)returnUrl;
/// Initialize the <code>KlarnaPaymentView</code>.
/// \param clientToken Client token received from Klarna when creating the session.
///
- (void)initializeWithClientToken:(NSString * _Nonnull)clientToken;
/// Performs a pre-assessment for this payment method category. Loads content into the
/// <code>KlarnaPaymentView</code>.
/// note:
///
/// Any existing content in the view (e.g. if you already called <code>load()</code> before) will be
/// replaced.
/// \param jsonData An optional string with order data to update the session. Formatted as JSON.
///
- (void)loadWithJsonData:(NSString * _Nullable)jsonData;
/// Renders an overview of the payment terms that have been authorized.
/// If your checkout offers the customer an opportunity to review the order after the payment
/// step (e.g. an order review page) it can make sense to present the payment method the customer
/// selected on a previous page.
/// This gives the customer a change to review the payment method and its terms to the user.
/// note:
///
/// Any existing content in the view (e.g. if you already called <code>load()</code> before) will be
/// replaced.
/// note:
///
/// Currently only specific payment methods and countries may be supported.
/// warning:
///
/// The session should be authorized.
- (void)loadPaymentReview;
/// Authorizes the session and evaluates whether an order can be created.
/// Merchant’s delegate will be called with successful/unsuccessful result of authorization.
/// \param jsonData An optional string to update the session. Formatted as JSON.
///
- (void)authorizeWithJsonData:(NSString * _Nullable)jsonData;
/// Authorizes the session and evaluates whether an order can be created.
/// Merchant’s delegate will be called with successful/unsuccessful result of authorization.
/// \param autoFinalize An optional flag used to turn off auto-finalization for the direct bank transfer payment method.
///
/// \param jsonData An optional string to update the session. Formatted as JSON.
///
- (void)authorizeWithAutoFinalize:(BOOL)autoFinalize jsonData:(NSString * _Nullable)jsonData;
/// Reauthorizes the session.
/// Call this if session details (order or customer info) have changed after authorization.
/// Merchant’s delegate will be called with successful/unsuccessful result of reauthorization.
/// \param jsonData An optional json string to update the session.
///
- (void)reauthorizeWithJsonData:(NSString * _Nullable)jsonData;
/// Finalizes the session.
/// Call this if you called <code>authorize()</code> with <code>autoFinalize</code> set to <code>false</code> and results in
/// <code>finalizeRequired</code> with a <code>true</code> value.
/// Merchant’s delegate will be called with successful/unsuccessful result of finalization.
/// note:
///
/// Method is called <code>finalise</code> with an “s” to avoid conflicts with the <code>NSObject</code> method of
/// the same name.
/// \param jsonData An optional string to update the session. Formatted as JSON.
///
- (void)finaliseWithJsonData:(NSString * _Nullable)jsonData;
@end

@class KlarnaPaymentOptions;
@class KlarnaEnvironment;
@class KlarnaRegion;
@class KlarnaResourceEndpoint;
@interface KlarnaPaymentView (SWIFT_EXTENSION(KlarnaPayments))
/// Payment method category this view will be / is displaying.
@property (nonatomic, readonly, copy) NSString * _Nonnull category;
/// Informs whether this <code>KlarnaPaymentView</code> should be displayed to the customer.
/// Will be false until a successful load() call has been performed.
@property (nonatomic, readonly) BOOL isLoaded;
/// Informs whether this PaymentView’s content is loaded.
/// True by default. Once it becomes false, it will not become true again.
@property (nonatomic, readonly) BOOL isAvalable;
/// Options for Klarna Payments integration
@property (nonatomic, readonly, strong) KlarnaPaymentOptions * _Nonnull paymentOptions;
/// Create a Klarna Payment View
/// note:
///
/// Klarna payment view will be initialized with frame <code>.zero</code>,
/// auto layout is the recommended way to manage the view’s layout.
/// note:
///
/// When the payment view is initialized, this initializer <em>wont</em> call <code>initialize()</code>
/// automatically. You need to call initialize yourself.
/// \param category Category of payment methods to be loaded.
///
/// \param eventListener A listener object that will receive events from this view.
///
- (nonnull instancetype)initWithCategory:(NSString * _Nonnull)category eventListener:(id <KlarnaPaymentEventListener> _Nonnull)eventListener;
/// Create a Klarna Payment View
/// note:
///
/// Klarna payment view will be initialized with frame <code>.zero</code>,
/// auto layout is the recommended way to manage the view’s layout.
/// note:
///
/// When the payment view is initialized, this initializer <em>wont</em> call <code>initialize()</code>
/// automatically. You need to call initialize yourself.
/// \param category Category of payment methods to be loaded.
///
/// \param returnUrl Your app’s custom URL scheme, specified in your app’s <code>CFBundleURLSchemes</code> field in the Info.plist.
///
/// \param eventListener A listener object that will receive events from this view.
///
- (nonnull instancetype)initWithCategory:(NSString * _Nonnull)category returnUrl:(NSURL * _Nonnull)returnUrl eventListener:(id <KlarnaPaymentEventListener> _Nonnull)eventListener;
/// Create a Klarna Payment View
/// note:
///
/// Klarna payment view will be initialized with frame <code>.zero</code>,
/// auto layout is the recommended way to manage the view’s layout.
/// note:
///
/// When the payment view is initialized, this initializer <em>wont</em> call <code>initialize()</code>
/// automatically. You need to call initialize yourself.
/// \param category Category of payment methods to be loaded.
///
/// \param returnUrl Your app’s custom URL scheme, specified in your app’s <code>CFBundleURLSchemes</code> field in the Info.plist.
///
/// \param eventListener A listener object that will receive events from this view.
///
/// \param environment Initialises the SDK with the specified Environment. For possible values check <code>KlarnaEnvironment</code>.
///
/// \param region Initialises the SDK with a specified Region. For possible values check <code>KlarnaRegion</code>.
///
- (nonnull instancetype)initWithCategory:(NSString * _Nonnull)category returnUrl:(NSURL * _Nonnull)returnUrl eventListener:(id <KlarnaPaymentEventListener> _Nonnull)eventListener environment:(KlarnaEnvironment * _Nonnull)environment region:(KlarnaRegion * _Nonnull)region;
/// Create a Klarna Payment View
/// note:
///
/// Klarna payment view will be initialized with frame <code>.zero</code>,
/// auto layout is the recommended way to manage the view’s layout.
/// note:
///
/// When the payment view is initialized, this initializer <em>wont</em> call <code>initialize()</code>
/// automatically. You need to call initialize yourself.
/// \param category Category of payment methods to be loaded.
///
/// \param eventListener A listener object that will receive events from this view.
///
/// \param resourceEndpoint Initialises the SDK with an alternative endpoint.
///
- (nonnull instancetype)initWithCategory:(NSString * _Nonnull)category eventListener:(id <KlarnaPaymentEventListener> _Nonnull)eventListener resourceEndpoint:(KlarnaResourceEndpoint * _Nonnull)resourceEndpoint;
/// Create a Klarna Payment View
/// note:
///
/// Klarna payment view will be initialized with frame <code>.zero</code>,
/// auto layout is the recommended way to manage the view’s layout.
/// note:
///
/// When the payment view is initialized, this initializer <em>wont</em> call <code>initialize()</code>
/// automatically. You need to call initialize yourself.
/// \param category Category of payment methods to be loaded.
///
/// \param returnUrl Your apps custom URL scheme <code>CFBundleURLSchemes</code>.
///
/// \param eventListener A listener object that will receive events from this view.
///
/// \param resourceEndpoint Initialises the SDK with an alternative endpoint.
///
- (nonnull instancetype)initWithCategory:(NSString * _Nonnull)category returnUrl:(NSURL * _Nonnull)returnUrl eventListener:(id <KlarnaPaymentEventListener> _Nonnull)eventListener resourceEndpoint:(KlarnaResourceEndpoint * _Nonnull)resourceEndpoint;
@end

@protocol KlarnaEventHandler;
@protocol KlarnaSizingDelegate;
@class UIScrollView;
@interface KlarnaPaymentView (SWIFT_EXTENSION(KlarnaPayments)) <KlarnaStandaloneComponent>
@property (nonatomic, strong) KlarnaRegion * _Nullable region;
@property (nonatomic, strong) KlarnaEnvironment * _Nullable environment;
@property (nonatomic, strong) KlarnaResourceEndpoint * _Nonnull resourceEndpoint;
@property (nonatomic, copy) NSURL * _Nullable returnURL;
@property (nonatomic) enum KlarnaTheme theme;
@property (nonatomic, strong) id <KlarnaEventHandler> _Nullable eventHandler;
@property (nonatomic) enum KlarnaLoggingLevel loggingLevel;
@property (nonatomic, readonly, copy) NSSet<NSString *> * _Nonnull products;
@property (nonatomic, readonly) CGFloat contentHeight;
@property (nonatomic, strong) id <KlarnaSizingDelegate> _Nullable sizingDelegate;
@property (nonatomic) BOOL isScrollEnabled;
@property (nonatomic) UIEdgeInsets contentInset;
@property (nonatomic, readonly) CGPoint contentOffset;
@property (nonatomic) enum UIScrollViewContentInsetAdjustmentBehavior contentInsetAdjustmentBehavior SWIFT_AVAILABILITY(ios,introduced=11.0);
@property (nonatomic) enum UIScrollViewKeyboardDismissMode keyboardDismissMode;
@property (nonatomic, strong) UIScrollView * _Nullable parentScrollView;
@property (nonatomic) BOOL adjustsParentScrollViewInsets;
@end

SWIFT_CLASS("_TtC14KlarnaPayments22KlarnaPaymentViewDebug")
@interface KlarnaPaymentViewDebug : KlarnaPaymentView
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
